import { CompletionContext, snippet } from "@codemirror/autocomplete";

const latexCommands = [
  { label: "\\frac", detail: "fraction", apply: snippet("\\frac{${1}}{${2}}") },
  { label: "\\sqrt", detail: "square root", apply: snippet("\\sqrt{${1}}") },
  { label: "\\sum", detail: "summation" },
  { label: "\\int", detail: "integral" },
  { label: "\\prod", detail: "product" },
  { label: "\\lim", detail: "limit" },
  { label: "\\infty", detail: "infinity" },
  { label: "\\alpha", detail: "greek letter" },
  { label: "\\beta", detail: "greek letter" },
  { label: "\\gamma", detail: "greek letter" },
  { label: "\\delta", detail: "greek letter" },
  { label: "\\epsilon", detail: "greek letter" },
  { label: "\\theta", detail: "greek letter" },
  { label: "\\lambda", detail: "greek letter" },
  { label: "\\mu", detail: "greek letter" },
  { label: "\\pi", detail: "greek letter" },
  { label: "\\sigma", detail: "greek letter" },
  { label: "\\omega", detail: "greek letter" },
  { label: "\\Gamma", detail: "greek letter" },
  { label: "\\Delta", detail: "greek letter" },
  { label: "\\Theta", detail: "greek letter" },
  { label: "\\Lambda", detail: "greek letter" },
  { label: "\\Sigma", detail: "greek letter" },
  { label: "\\Omega", detail: "greek letter" },
  { label: "\\sin", detail: "sine" },
  { label: "\\cos", detail: "cosine" },
  { label: "\\tan", detail: "tangent" },
  { label: "\\log", detail: "logarithm" },
  { label: "\\ln", detail: "natural log" },
  { label: "\\exp", detail: "exponential" },
  { label: "\\lim", detail: "limit" },
  { label: "\\sup", detail: "supremum" },
  { label: "\\inf", detail: "infimum" },
  { label: "\\max", detail: "maximum" },
  { label: "\\min", detail: "minimum" },
  { label: "\\left(", detail: "left paren", apply: snippet("\\left(${1}\\right)") },
  { label: "\\left[", detail: "left bracket", apply: snippet("\\left[${1}\\right]") },
  { label: "\\left\\{", detail: "left brace", apply: snippet("\\left\\{${1}\\right\\}") },
  { label: "\\begin{align}", detail: "align env", apply: snippet("\\begin{align}\n\t${1}\n\\end{align}") },
  { label: "\\begin{equation}", detail: "equation env", apply: snippet("\\begin{equation}\n\t${1}\n\\end{equation}") },
  { label: "\\begin{matrix}", detail: "matrix env", apply: snippet("\\begin{matrix}\n\t${1}\n\\end{matrix}") },
  { label: "\\begin{pmatrix}", detail: "paren matrix", apply: snippet("\\begin{pmatrix}\n\t${1}\n\\end{pmatrix}") },
  { label: "\\begin{bmatrix}", detail: "bracket matrix", apply: snippet("\\begin{bmatrix}\n\t${1}\n\\end{bmatrix}") },
  { label: "\\mathbb", detail: "blackboard bold", apply: snippet("\\mathbb{${1}}") },
  { label: "\\mathcal", detail: "calligraphic", apply: snippet("\\mathcal{${1}}") },
  { label: "\\mathbf", detail: "bold", apply: snippet("\\mathbf{${1}}") },
  { label: "\\mathit", detail: "italic", apply: snippet("\\mathit{${1}}") },
  { label: "\\text", detail: "text mode", apply: snippet("\\text{${1}}") },
  { label: "\\cdot", detail: "dot product" },
  { label: "\\times", detail: "cross product" },
  { label: "\\div", detail: "division" },
  { label: "\\pm", detail: "plus-minus" },
  { label: "\\mp", detail: "minus-plus" },
  { label: "\\leq", detail: "less or equal" },
  { label: "\\geq", detail: "greater or equal" },
  { label: "\\neq", detail: "not equal" },
  { label: "\\approx", detail: "approximately" },
  { label: "\\equiv", detail: "equivalent" },
  { label: "\\in", detail: "element of" },
  { label: "\\notin", detail: "not element of" },
  { label: "\\subset", detail: "subset" },
  { label: "\\subseteq", detail: "subset or equal" },
  { label: "\\cup", detail: "union" },
  { label: "\\cap", detail: "intersection" },
  { label: "\\emptyset", detail: "empty set" },
  { label: "\\forall", detail: "for all" },
  { label: "\\exists", detail: "exists" },
  { label: "\\nabla", detail: "nabla/del" },
  { label: "\\partial", detail: "partial derivative" },
  { label: "\\rightarrow", detail: "right arrow" },
  { label: "\\Rightarrow", detail: "implies" },
  { label: "\\leftarrow", detail: "left arrow" },
  { label: "\\Leftarrow", detail: "implied by" },
  { label: "\\leftrightarrow", detail: "bidirectional" },
  { label: "\\Leftrightarrow", detail: "if and only if" },
  { label: "\\prime", detail: "prime" },
  { label: "\\ldots", detail: "ellipsis" },
  { label: "\\cdots", detail: "centered dots" },
  { label: "\\vdots", detail: "vertical dots" },
  { label: "\\ddots", detail: "diagonal dots" },
];

export function latexCompletions(context) {
  const word = context.matchBefore(/\\[a-zA-Z]*/);
  if (!word || (word.from === word.to && !context.explicit)) {
    return null;
  }
  
  return {
    from: word.from,
    options: latexCommands,
    validFor: /^\\[a-zA-Z]*$/
  };
}
