// Helper to create matrix grid labels (just the dots, no wrapper)
function matrixGrid(rows, cols) {
  const cells = Array(rows)
    .fill()
    .map(() => Array(cols).fill("\\cdot").join("\\!&\\!"))
    .join("\\\\");
  return cells;
}

// Generate grouped matrix/table commands (each type has 1x1, 2x2, 3x3 as subcommands)
function generateMatrixCommands() {
  const matrixTypes = [
    { env: 'pmatrix', label1x1: '\\left(\\cdot\\right)', left: '\\left(', right: '\\right)', desc: 'parentheses ( )' },
    { env: 'bmatrix', label1x1: '\\left[\\cdot\\right]', left: '\\left[', right: '\\right]', desc: 'brackets [ ]' },
    { env: 'Bmatrix', label1x1: '\\left\\{\\cdot\\right\\}', left: '\\left\\{', right: '\\right\\}', desc: 'braces { }' },
    { env: 'vmatrix', label1x1: '\\left|\\cdot\\right|', left: '\\left\\vert', right: '\\right\\vert', desc: '| |', isDeterminant: true },
    { env: 'Vmatrix', label1x1: '\\left\\|\\cdot\\right\\|', left: '\\left\\Vert', right: '\\right\\Vert', desc: 'double bars ‖ ‖' },
    { env: 'matrix', label1x1: '\\cdot', left: '', right: '', desc: 'no delimiters' },
  ];

  const sizes = [
    { size: 1, placeholders: '${1}' },
    { size: 2, placeholders: '${1} & ${2} \\\\\n  ${3} & ${4}' },
    { size: 3, placeholders: '${1} & ${2} & ${3} \\\\\n  ${4} & ${5} & ${6} \\\\\n  ${7} & ${8} & ${9}' },
  ];

  const commands = [];

  // Generate grouped commands for each matrix type
  for (const type of matrixTypes) {
    const matrixWord = type.isDeterminant ? 'determinant' : 'matrix';
    const subcommands = sizes.map(({ size, placeholders }) => ({
      label: size === 1
        ? type.label1x1
        : `${type.left}\\begin{smallmatrix}${matrixGrid(size, size)}\\end{smallmatrix}${type.right}`,
      latex: `\\begin{${type.env}}\n  ${placeholders}\n\\end{${type.env}}`,
      tooltip: `${size}×${size} ${matrixWord} ${type.desc}`,
    }));

    commands.push({
      label: subcommands[0].label,
      latex: subcommands[0].latex,
      tooltip: `Matrix ${type.desc}`,
      subcommands,
    });
  }

  // Add angle matrix group
  const angleSubcommands = sizes.map(({ size, placeholders }) => ({
    label: size === 1
      ? '\\langle\\cdot\\rangle'
      : `\\left\\langle\\begin{smallmatrix}${matrixGrid(size, size)}\\end{smallmatrix}\\right\\rangle`,
    latex: `\\left\\langle\\begin{matrix}${placeholders}\\end{matrix}\\right\\rangle`,
    tooltip: `${size}×${size} angle brackets ⟨ ⟩`,
  }));

  commands.push({
    label: angleSubcommands[0].label,
    latex: angleSubcommands[0].latex,
    tooltip: 'Matrix angle brackets ⟨ ⟩',
    subcommands: angleSubcommands,
  });

  return commands;
}

export const toolbarCommands = [
  {
    category: "Common",
    icon: "\\Sigma",
    commands: [
      {
        label: "\\frac{a}{b}",
        latex: "\\frac{${1}}{${2}}",
        tooltip: "Fraction",
      },
      {
        label: "\\frac{\\mathrm{d}}{\\mathrm{d}x}",
        latex: "\\frac{\\mathrm{d}}{\\mathrm{d}x}",
        tooltip: "Derivative d/dx",
      },
      {
        label: "\\frac{\\partial}{\\partial x}",
        latex: "\\frac{\\partial}{\\partial x}",
        tooltip: "Partial derivative",
      },
      {
        label: "\\frac{\\partial^2}{\\partial x^2}",
        latex: "\\frac{\\partial^2}{\\partial x^2}",
        tooltip: "Second partial derivative",
      },
      { label: "\\sqrt{x}", latex: "\\sqrt{${1}}", tooltip: "Square root" },
      {
        label: "\\sqrt[n]{x}",
        latex: "\\sqrt[${1}]{${2}}",
        tooltip: "Nth root",
      },
      { label: "x^n", latex: "${1}^{${2}}", tooltip: "Superscript" },
      { label: "x_n", latex: "${1}_{${2}}", tooltip: "Subscript" },
      { label: "x_n^m", latex: "${1}_{${2}}^{${3}}", tooltip: "Sub & superscript" },
      { label: "\\sum", latex: "\\sum_{${1}}^{${2}}", tooltip: "Summation ∑" },
      {
        label: "\\prod", latex: "\\prod_{${1}}^{${2}}", tooltip: "Product ∏",
        subcommands: [
          { label: "\\prod", latex: "\\prod_{${1}}^{${2}}", tooltip: "Single product ∏" },
          { label: "\\coprod", latex: "\\coprod_{${1}}^{${2}}", tooltip: "Coproduct ∐" },
        ]
      },
      {
        label: "\\int",
        latex: "\\int_{${1}}^{${2}}",
        tooltip: "Integral",
        subcommands: [
          { label: "\\int", latex: "\\int_{${1}}^{${2}}", tooltip: "Single integral ∫" },
          { label: "\\iint", latex: "\\iint_{${1}}^{${2}}", tooltip: "Double integral ∬" },
          { label: "\\iiint", latex: "\\iiint_{${1}}^{${2}}", tooltip: "Triple integral ∭" },
        ]
      },
      {
        label: "\\oint",
        latex: "\\oint_{${1}}",
        tooltip: "Contour integral",
        subcommands: [
          { label: "\\oint", latex: "\\oint_{${1}}", tooltip: "Contour integral ∮" },
          { label: "\\oiint", latex: "\\oiint_{${1}}", tooltip: "Surface integral ∯" },
          { label: "\\oiiint", latex: "\\oiiint_{${1}}", tooltip: "Volume integral ∰" },
        ],
      },
      {
        label: "\\lim_{x \\to 0}",
        latex: "\\lim_{${1} \\to ${2}}",
        tooltip: "Limit",
      },
    ],
  },
  {
    category: "Braces and Matrices",
    icon: "[\\cdot]",
    commands: [
      // Matrices (grouped by delimiter type)
      ...generateMatrixCommands(),
      // Tables using array environment (grouped)
      {
        label: "\\boxed{\\cdot}",
        latex: "\\begin{array}{|c|}\n\\hline\n  ${1} \\\\\n\\hline\n\\end{array}",
        tooltip: "Table with borders",
        subcommands: [
          {
            label: "\\boxed{\\cdot}",
            latex: "\\begin{array}{|c|}\n\\hline\n  ${1} \\\\\n\\hline\n\\end{array}",
            tooltip: "1×1 table with borders",
          },
          {
            label: "{\\scriptstyle\\begin{array}{|c|c|}\\hline\\cdot&\\cdot\\\\\\hline\\cdot&\\cdot\\\\\\hline\\end{array}}",
            latex: "\\begin{array}{|c|c|}\n\\hline\n  ${1} & ${2} \\\\\n\\hline\n  ${3} & ${4} \\\\\n\\hline\n\\end{array}",
            tooltip: "2×2 table with borders",
          },
          {
            label: "{\\scriptscriptstyle\\begin{array}{|c|c|c|}\\hline\\cdot&\\cdot&\\cdot\\\\\\hline\\cdot&\\cdot&\\cdot\\\\\\hline\\cdot&\\cdot&\\cdot\\\\\\hline\\end{array}}",
            latex: "\\begin{array}{|c|c|c|}\n\\hline\n  ${1} & ${2} & ${3} \\\\\n\\hline\n  ${4} & ${5} & ${6} \\\\\n\\hline\n  ${7} & ${8} & ${9} \\\\\n\\hline\n\\end{array}",
            tooltip: "3×3 table with borders",
          },
        ],
      },
      // Other delimiters
      {
        label: "\\lceil\\cdot \\rceil",
        latex: "\\left\\lceil ${1} \\right\\rceil",
        tooltip: "Ceiling brackets ⌈ ⌉",
      },
      {
        label: "\\lfloor\\cdot \\rfloor",
        latex: "\\left\\lfloor ${1} \\right\\rfloor",
        tooltip: "Floor brackets ⌊ ⌋",
      },
      {
        label: "\\lgroup\\cdot \\rgroup",
        latex: "\\left\\lgroup ${1} \\right\\rgroup",
        tooltip: "Group brackets ⟮ ⟯",
      },
      {
        label: "\\lmoustache\\cdot \\rmoustache",
        latex: "\\left\\lmoustache ${1} \\right\\rmoustache",
        tooltip: "Moustache brackets ⎰ ⎱",
      },
      {
        label: "\\llbracket\\cdot \\rrbracket",
        latex: "\\llbracket ${1} \\rrbracket",
        tooltip: "Double brackets ⟦ ⟧ (fixed size, MathJax approximation)",
      },
      {
        label: "\\left.\\cdot \\right|",
        latex: "\\left.${1}\\right|",
        tooltip: "Invisible left delimiter",
      },
      {
        label: "\\left|\\cdot \\right.",
        latex: "\\left|${1}\\right.",
        tooltip: "Invisible right delimiter",
      },
      // Binomial coefficient
      {
        label: "\\binom{n}{k}",
        latex: "\\binom{${1}}{${2}}",
        tooltip: "Binomial coefficient",
      },
      // Cases (piecewise)
      {
        label: "\\begin{cases}\\scriptsize\\text{if}\\\\[-.5em]\\scriptsize\\text{else}\\end{cases}",
        latex: "\\begin{cases}\n  ${1} & \\text{if } ${2} \\\\\n  ${3} & \\text{otherwise}\n\\end{cases}",
        tooltip: "Cases (piecewise)",
      },
    ],
  },
  {
    category: "Greek",
    icon: "\\varepsilon",
    commands: [
      { label: "\\alpha", latex: "\\alpha", tooltip: "alpha" },
      { label: "\\beta", latex: "\\beta", tooltip: "beta" },
      { label: "\\gamma", latex: "\\gamma", tooltip: "gamma" },
      { label: "\\delta", latex: "\\delta", tooltip: "delta" },
      { label: "\\epsilon", latex: "\\epsilon", tooltip: "epsilon" },
      { label: "\\varepsilon", latex: "\\varepsilon", tooltip: "variant epsilon" },
      { label: "\\zeta", latex: "\\zeta", tooltip: "zeta" },
      { label: "\\eta", latex: "\\eta", tooltip: "eta" },
      { label: "\\theta", latex: "\\theta", tooltip: "theta" },
      { label: "\\vartheta", latex: "\\vartheta", tooltip: "variant theta" },
      { label: "\\iota", latex: "\\iota", tooltip: "iota" },
      { label: "\\kappa", latex: "\\kappa", tooltip: "kappa" },
      { label: "\\varkappa", latex: "\\varkappa", tooltip: "variant kappa" },
      { label: "\\lambda", latex: "\\lambda", tooltip: "lambda" },
      { label: "\\mu", latex: "\\mu", tooltip: "mu" },
      { label: "\\nu", latex: "\\nu", tooltip: "nu" },
      { label: "\\xi", latex: "\\xi", tooltip: "xi" },
      { label: "o", latex: "o", tooltip: "omicron" },
      { label: "\\pi", latex: "\\pi", tooltip: "pi" },
      { label: "\\varpi", latex: "\\varpi", tooltip: "variant pi" },
      { label: "\\rho", latex: "\\rho", tooltip: "rho" },
      { label: "\\varrho", latex: "\\varrho", tooltip: "variant rho" },
      { label: "\\sigma", latex: "\\sigma", tooltip: "sigma" },
      { label: "\\varsigma", latex: "\\varsigma", tooltip: "final sigma" },
      { label: "\\tau", latex: "\\tau", tooltip: "tau" },
      { label: "\\upsilon", latex: "\\upsilon", tooltip: "upsilon" },
      { label: "\\phi", latex: "\\phi", tooltip: "phi" },
      { label: "\\varphi", latex: "\\varphi", tooltip: "variant phi" },
      { label: "\\chi", latex: "\\chi", tooltip: "chi" },
      { label: "\\psi", latex: "\\psi", tooltip: "psi" },
      { label: "\\omega", latex: "\\omega", tooltip: "omega" },
      { label: "\\digamma", latex: "\\digamma", tooltip: "digamma" },
      { label: "\\Gamma", latex: "\\Gamma", tooltip: "Gamma" },
      { label: "\\Delta", latex: "\\Delta", tooltip: "Delta" },
      { label: "\\Theta", latex: "\\Theta", tooltip: "Theta" },
      { label: "\\Lambda", latex: "\\Lambda", tooltip: "Lambda" },
      { label: "\\Xi", latex: "\\Xi", tooltip: "Xi" },
      { label: "\\Pi", latex: "\\Pi", tooltip: "Pi" },
      { label: "\\Sigma", latex: "\\Sigma", tooltip: "Sigma" },
      { label: "\\Upsilon", latex: "\\Upsilon", tooltip: "Upsilon" },
      { label: "\\Phi", latex: "\\Phi", tooltip: "Phi" },
      { label: "\\Psi", latex: "\\Psi", tooltip: "Psi" },
      { label: "\\Omega", latex: "\\Omega", tooltip: "Omega" },
    ],
  },
  {
    category: "Relations",
    icon: "\\neq",
    commands: [
      { label: "=", latex: "=", tooltip: "Equal" },
      { label: "\\neq", latex: "\\neq", tooltip: "Not equal" },
      { label: "\\equiv", latex: "\\equiv", tooltip: "Equivalent" },
      { label: "\\not\\equiv", latex: "\\not\\equiv", tooltip: "Not equivalent" },
      { label: "<", latex: "<", tooltip: "Less than" },
      { label: ">", latex: ">", tooltip: "Greater than" },
      { label: "\\leq", latex: "\\leq", tooltip: "Less than or equal" },
      { label: "\\geq", latex: "\\geq", tooltip: "Greater than or equal" },
      { label: "\\nless", latex: "\\nless", tooltip: "Not less than" },
      { label: "\\ngtr", latex: "\\ngtr", tooltip: "Not greater than" },
      { label: "\\nleq", latex: "\\nleq", tooltip: "Not less or equal" },
      { label: "\\ngeq", latex: "\\ngeq", tooltip: "Not greater or equal" },
      { label: "\\prec", latex: "\\prec", tooltip: "Precedes" },
      { label: "\\succ", latex: "\\succ", tooltip: "Succeeds" },
      { label: "\\ll", latex: "\\ll", tooltip: "Much less than" },
      { label: "\\gg", latex: "\\gg", tooltip: "Much greater than" },
      { label: "\\sqsubset", latex: "\\sqsubset", tooltip: "Square subset" },
      { label: "\\sqsupset", latex: "\\sqsupset", tooltip: "Square superset" },
      { label: "\\frown", latex: "\\frown", tooltip: "Frown" },
      { label: "\\smile", latex: "\\smile", tooltip: "Smile" },
      { label: "\\vdash", latex: "\\vdash", tooltip: "Proves" },
      { label: "\\perp", latex: "\\perp", tooltip: "Perpendicular" },
      { label: "\\mid", latex: "\\mid", tooltip: "Divides" },
      { label: "\\parallel", latex: "\\parallel", tooltip: "Parallel" },
      { label: "\\bowtie", latex: "\\bowtie", tooltip: "Bowtie" },
      { label: "\\approx", latex: "\\approx", tooltip: "Approximately ≈" },
      { label: "\\approxeq", latex: "\\approxeq", tooltip: "Approximately equal ≊" },
      { label: "\\sim", latex: "\\sim", tooltip: "Similar ∼" },
      { label: "\\simeq", latex: "\\simeq", tooltip: "Similar equal ≃" },
      { label: "\\cong", latex: "\\cong", tooltip: "Congruent ≅" },
      { label: "\\asymp", latex: "\\asymp", tooltip: "Asymptotic ≍" },
      { label: "\\doteq", latex: "\\doteq", tooltip: "Dot equals ≐" },
      { label: "\\doteqdot", latex: "\\doteqdot", tooltip: "Dot equals dot ≑" },
      { label: "\\fallingdotseq", latex: "\\fallingdotseq", tooltip: "Falling dot seq ≒" },
      { label: "\\risingdotseq", latex: "\\risingdotseq", tooltip: "Rising dot seq ≓" },
      { label: "\\eqcirc", latex: "\\eqcirc", tooltip: "Equals circle ≖" },
      { label: "\\circeq", latex: "\\circeq", tooltip: "Circle equals ≗" },
      { label: "\\triangleq", latex: "\\triangleq", tooltip: "Triangle equals ≜" },
      { label: "\\bumpeq", latex: "\\bumpeq", tooltip: "Bumpy equals ≏" },
      { label: "\\Bumpeq", latex: "\\Bumpeq", tooltip: "Bumpy equals ≎" },
      { label: "\\eqsim", latex: "\\eqsim", tooltip: "Equals similar ≂" },
      { label: "\\thicksim", latex: "\\thicksim", tooltip: "Thick sim" },
      { label: "\\thickapprox", latex: "\\thickapprox", tooltip: "Thick approx" },
      { label: "\\backsim", latex: "\\backsim", tooltip: "Back sim ∽" },
      { label: "\\backsimeq", latex: "\\backsimeq", tooltip: "Back sim eq ⋍" },
      { label: "\\propto", latex: "\\propto", tooltip: "Proportional ∝" },
      { label: "\\varpropto", latex: "\\varpropto", tooltip: "Var proportional ∝" },
      { label: "\\leqq", latex: "\\leqq", tooltip: "Less equal equal ≦" },
      { label: "\\geqq", latex: "\\geqq", tooltip: "Greater equal equal ≧" },
      { label: "\\leqslant", latex: "\\leqslant", tooltip: "Less eq slant ⩽" },
      { label: "\\geqslant", latex: "\\geqslant", tooltip: "Greater eq slant ⩾" },
      { label: "\\eqslantless", latex: "\\eqslantless", tooltip: "Eq slant less ⪕" },
      { label: "\\eqslantgtr", latex: "\\eqslantgtr", tooltip: "Eq slant greater ⪖" },
      { label: "\\lesssim", latex: "\\lesssim", tooltip: "Less similar ≲" },
      { label: "\\gtrsim", latex: "\\gtrsim", tooltip: "Greater similar ≳" },
      { label: "\\lessapprox", latex: "\\lessapprox", tooltip: "Less approx ⪅" },
      { label: "\\gtrapprox", latex: "\\gtrapprox", tooltip: "Greater approx ⪆" },
      { label: "\\lessgtr", latex: "\\lessgtr", tooltip: "Less greater ≶" },
      { label: "\\gtrless", latex: "\\gtrless", tooltip: "Greater less ≷" },
      { label: "\\lesseqgtr", latex: "\\lesseqgtr", tooltip: "Less eq greater ⋚" },
      { label: "\\gtreqless", latex: "\\gtreqless", tooltip: "Greater eq less ⋛" },
      { label: "\\lesseqqgtr", latex: "\\lesseqqgtr", tooltip: "Less eqq greater ⪋" },
      { label: "\\gtreqqless", latex: "\\gtreqqless", tooltip: "Greater eqq less ⪌" },
      { label: "\\lll", latex: "\\lll", tooltip: "Much much less ⋘" },
      { label: "\\ggg", latex: "\\ggg", tooltip: "Much much greater ⋙" },
      { label: "\\lessdot", latex: "\\lessdot", tooltip: "Less dot ⋖" },
      { label: "\\gtrdot", latex: "\\gtrdot", tooltip: "Greater dot ⋗" },
      { label: "\\preccurlyeq", latex: "\\preccurlyeq", tooltip: "Prec curly eq ≼" },
      { label: "\\succcurlyeq", latex: "\\succcurlyeq", tooltip: "Succ curly eq ≽" },
      { label: "\\preceq", latex: "\\preceq", tooltip: "Precedes equal ⪯" },
      { label: "\\succeq", latex: "\\succeq", tooltip: "Succeeds equal ⪰" },
      { label: "\\precsim", latex: "\\precsim", tooltip: "Prec sim ≾" },
      { label: "\\succsim", latex: "\\succsim", tooltip: "Succ sim ≿" },
      { label: "\\precapprox", latex: "\\precapprox", tooltip: "Prec approx ⪷" },
      { label: "\\succapprox", latex: "\\succapprox", tooltip: "Succ approx ⪸" },
      { label: "\\curlyeqprec", latex: "\\curlyeqprec", tooltip: "Curly eq prec ⋞" },
      { label: "\\curlyeqsucc", latex: "\\curlyeqsucc", tooltip: "Curly eq succ ⋟" },
      { label: "\\subseteqq", latex: "\\subseteqq", tooltip: "Subset eqq ⫅" },
      { label: "\\supseteqq", latex: "\\supseteqq", tooltip: "Superset eqq ⫆" },
      { label: "\\Subset", latex: "\\Subset", tooltip: "Double subset ⋐" },
      { label: "\\Supset", latex: "\\Supset", tooltip: "Double superset ⋑" },
      { label: "\\sqsubseteq", latex: "\\sqsubseteq", tooltip: "Square subset eq ⊑" },
      { label: "\\sqsupseteq", latex: "\\sqsupseteq", tooltip: "Square superset eq ⊒" },
      { label: "\\models", latex: "\\models", tooltip: "Models ⊨" },
      { label: "\\vDash", latex: "\\vDash", tooltip: "Double vdash ⊨" },
      { label: "\\Vdash", latex: "\\Vdash", tooltip: "V dash ⊩" },
      { label: "\\Vvdash", latex: "\\Vvdash", tooltip: "VV dash ⊪" },
      { label: "\\dashv", latex: "\\dashv", tooltip: "Dash v ⊣" },
      { label: "\\between", latex: "\\between", tooltip: "Between ≬" },
      { label: "\\pitchfork", latex: "\\pitchfork", tooltip: "Pitchfork ⋔" },
      { label: "\\shortmid", latex: "\\shortmid", tooltip: "Short mid" },
      { label: "\\shortparallel", latex: "\\shortparallel", tooltip: "Short parallel" },
      { label: "\\smallfrown", latex: "\\smallfrown", tooltip: "Small frown ⌢" },
      { label: "\\smallsmile", latex: "\\smallsmile", tooltip: "Small smile ⌣" },
      { label: "\\vartriangleleft", latex: "\\vartriangleleft", tooltip: "Var triangle left ⊲" },
      { label: "\\vartriangleright", latex: "\\vartriangleright", tooltip: "Var triangle right ⊳" },
      { label: "\\trianglelefteq", latex: "\\trianglelefteq", tooltip: "Triangle left eq ⊴" },
      { label: "\\trianglerighteq", latex: "\\trianglerighteq", tooltip: "Triangle right eq ⊵" },
      { label: "\\backepsilon", latex: "\\backepsilon", tooltip: "Back epsilon ∍" },
      { label: "\\Join", latex: "\\Join", tooltip: "Join ⋈" },
      { label: "\\multimap", latex: "\\multimap", tooltip: "Multimap ⊸" },
      { label: "\\in", latex: "\\in", tooltip: "Element of ∈" },
      { label: "\\notin", latex: "\\notin", tooltip: "Not element of ∉" },
      { label: "\\subset", latex: "\\subset", tooltip: "Subset ⊂" },
      { label: "\\subseteq", latex: "\\subseteq", tooltip: "Subset or equal ⊆" },
      { label: "\\supset", latex: "\\supset", tooltip: "Superset ⊃" },
      { label: "\\supseteq", latex: "\\supseteq", tooltip: "Superset or equal ⊇" },
    ],
  },
  {
    category: "Operators",
    icon: "×",
    commands: [
      { label: "+", latex: "+", tooltip: "Plus +" },
      { label: "-", latex: "-", tooltip: "Minus −" },
      { label: "\\pm", latex: "\\pm", tooltip: "Plus minus ±" },
      { label: "\\mp", latex: "\\mp", tooltip: "Minus plus ∓" },
      { label: "\\times", latex: "\\times", tooltip: "Times ×" },
      { label: "\\div", latex: "\\div", tooltip: "Division ÷" },
      { label: "\\cdot", latex: "\\cdot", tooltip: "Center dot ⋅" },
      { label: "\\ast", latex: "\\ast", tooltip: "Asterisk ∗" },
      {
        label: "\\circ",
        latex: "\\circ",
        tooltip: "Circle ∘",
        subcommands: [
          { label: "\\circ", latex: "\\circ", tooltip: "Circle ∘" },
          { label: "\\bigcirc", latex: "\\bigcirc", tooltip: "Big circle ◯" },
        ],
      },
      { label: "\\bullet", latex: "\\bullet", tooltip: "Bullet ∙" },
      {
        label: "\\wedge",
        latex: "\\wedge",
        tooltip: "Wedge/AND ∧",
        subcommands: [
          { label: "\\wedge", latex: "\\wedge", tooltip: "Wedge/AND ∧" },
          { label: "\\bigwedge", latex: "\\bigwedge_{${1}}", tooltip: "Big wedge ⋀" },
        ],
      },
      {
        label: "\\vee",
        latex: "\\vee",
        tooltip: "Vee/OR ∨",
        subcommands: [
          { label: "\\vee", latex: "\\vee", tooltip: "Vee/OR ∨" },
          { label: "\\bigvee", latex: "\\bigvee_{${1}}", tooltip: "Big vee ⋁" },
        ],
      },
      {
        label: "\\cap",
        latex: "\\cap",
        tooltip: "Intersection ∩",
        subcommands: [
          { label: "\\cap", latex: "\\cap", tooltip: "Intersection ∩" },
          { label: "\\bigcap", latex: "\\bigcap_{${1}}", tooltip: "Big intersection ⋂" },
        ],
      },
      {
        label: "\\cup",
        latex: "\\cup",
        tooltip: "Union ∪",
        subcommands: [
          { label: "\\cup", latex: "\\cup", tooltip: "Union ∪" },
          { label: "\\bigcup", latex: "\\bigcup_{${1}}", tooltip: "Big union ⋃" },
        ],
      },
      { label: "\\sqcap", latex: "\\sqcap", tooltip: "Square cap ⊓" },
      {
        label: "\\sqcup",
        latex: "\\sqcup",
        tooltip: "Square cup ⊔",
        subcommands: [
          { label: "\\sqcup", latex: "\\sqcup", tooltip: "Square cup ⊔" },
          { label: "\\bigsqcup", latex: "\\bigsqcup_{${1}}", tooltip: "Big square cup ⨆" },
        ],
      },
      {
        label: "\\uplus",
        latex: "\\uplus",
        tooltip: "Multiset union ⊎",
        subcommands: [
          { label: "\\uplus", latex: "\\uplus", tooltip: "Multiset union ⊎" },
          { label: "\\biguplus", latex: "\\biguplus_{${1}}", tooltip: "Big multiset union ⨄" },
        ],
      },
      {
        label: "\\oplus",
        latex: "\\oplus",
        tooltip: "Circled plus ⊕",
        subcommands: [
          { label: "\\oplus", latex: "\\oplus", tooltip: "Circled plus ⊕" },
          { label: "\\bigoplus", latex: "\\bigoplus_{${1}}", tooltip: "Big circled plus ⨁" },
        ],
      },
      { label: "\\ominus", latex: "\\ominus", tooltip: "Circled minus ⊖" },
      {
        label: "\\otimes",
        latex: "\\otimes",
        tooltip: "Circled times ⊗",
        subcommands: [
          { label: "\\otimes", latex: "\\otimes", tooltip: "Circled times ⊗" },
          { label: "\\bigotimes", latex: "\\bigotimes_{${1}}", tooltip: "Big circled times ⨂" },
        ],
      },
      { label: "\\oslash", latex: "\\oslash", tooltip: "Circled slash ⊘" },
      {
        label: "\\odot",
        latex: "\\odot",
        tooltip: "Circled dot ⊙",
        subcommands: [
          { label: "\\odot", latex: "\\odot", tooltip: "Circled dot ⊙" },
          { label: "\\bigodot", latex: "\\bigodot_{${1}}", tooltip: "Big circled dot ⨀" },
        ],
      },
      { label: "\\circledast", latex: "\\circledast", tooltip: "Circled asterisk ⊛" },
      { label: "\\circledcirc", latex: "\\circledcirc", tooltip: "Circled circle ⊚" },
      { label: "\\circleddash", latex: "\\circleddash", tooltip: "Circled dash ⊝" },
      { label: "\\boxplus", latex: "\\boxplus", tooltip: "Boxed plus ⊞" },
      { label: "\\boxminus", latex: "\\boxminus", tooltip: "Boxed minus ⊟" },
      { label: "\\boxtimes", latex: "\\boxtimes", tooltip: "Boxed times ⊠" },
      { label: "\\boxdot", latex: "\\boxdot", tooltip: "Boxed dot ⊡" },
      {
        label: "\\setminus",
        latex: "\\setminus",
        tooltip: "Set minus ∖",
        subcommands: [
          { label: "\\setminus", latex: "\\setminus", tooltip: "Set minus ∖" },
          { label: "\\smallsetminus", latex: "\\smallsetminus", tooltip: "Small set minus ∖" },
        ],
      },
      { label: "\\wr", latex: "\\wr", tooltip: "Wreath product ≀" },
      { label: "\\amalg", latex: "\\amalg", tooltip: "Amalgamation ⨿" },
      { label: "\\ltimes", latex: "\\ltimes", tooltip: "Left semidirect ⋉" },
      { label: "\\rtimes", latex: "\\rtimes", tooltip: "Right semidirect ⋊" },
      { label: "\\leftthreetimes", latex: "\\leftthreetimes", tooltip: "Left three times ⋋" },
      { label: "\\rightthreetimes", latex: "\\rightthreetimes", tooltip: "Right three times ⋌" },
      { label: "\\intercal", latex: "\\intercal", tooltip: "Intercal ⊺" },
      { label: "\\divideontimes", latex: "\\divideontimes", tooltip: "Divide on times ⋇" },
      {
        label: "\\bmod",
        latex: "\\bmod",
        tooltip: "Modulo",
        subcommands: [
          { label: "\\bmod", latex: "\\bmod", tooltip: "Binary mod" },
          { label: "a \\pmod{b}", latex: "${1} \\pmod{${2}}", tooltip: "Parenthesized mod" },
        ],
      },
      { label: "\\barwedge", latex: "\\barwedge", tooltip: "Bar wedge ⊼" },
      { label: "\\veebar", latex: "\\veebar", tooltip: "Vee bar ⊻" },
      { label: "\\doublebarwedge", latex: "\\doublebarwedge", tooltip: "Double bar wedge ⩞" },
      { label: "\\curlyvee", latex: "\\curlyvee", tooltip: "Curly vee ⋎" },
      { label: "\\curlywedge", latex: "\\curlywedge", tooltip: "Curly wedge ⋏" },
      { label: "\\Cap", latex: "\\Cap", tooltip: "Double cap ⋒" },
      { label: "\\Cup", latex: "\\Cup", tooltip: "Double cup ⋓" },
      { label: "\\lhd", latex: "\\lhd", tooltip: "Left triangular ⊲" },
      { label: "\\rhd", latex: "\\rhd", tooltip: "Right triangular ⊳" },
      { label: "\\unlhd", latex: "\\unlhd", tooltip: "Unlhd ⊴" },
      { label: "\\unrhd", latex: "\\unrhd", tooltip: "Unrhd ⊵" },
      { label: "\\forall", latex: "\\forall", tooltip: "For all ∀" },
      { label: "\\exists", latex: "\\exists", tooltip: "Exists ∃" },
      { label: "\\neg", latex: "\\neg", tooltip: "Logical NOT ¬" },
    ],
  },
  {
    category: "Arrows",
    icon: "→",
    commands: [
      { label: "\\to", latex: "\\to", tooltip: "Right arrow" },
      { label: "\\rightarrow", latex: "\\rightarrow", tooltip: "Right arrow" },
      { label: "\\leftarrow", latex: "\\leftarrow", tooltip: "Left arrow" },
      { label: "\\leftrightarrow", latex: "\\leftrightarrow", tooltip: "Left-right arrow" },
      { label: "\\Rightarrow", latex: "\\Rightarrow", tooltip: "Implies" },
      { label: "\\Leftarrow", latex: "\\Leftarrow", tooltip: "Implied by" },
      { label: "\\Leftrightarrow", latex: "\\Leftrightarrow", tooltip: "If and only if" },
      { label: "\\longrightarrow", latex: "\\longrightarrow", tooltip: "Long right arrow" },
      { label: "\\longleftarrow", latex: "\\longleftarrow", tooltip: "Long left arrow" },
      { label: "\\longleftrightarrow", latex: "\\longleftrightarrow", tooltip: "Long left-right arrow" },
      { label: "\\Longrightarrow", latex: "\\Longrightarrow", tooltip: "Long implies" },
      { label: "\\Longleftarrow", latex: "\\Longleftarrow", tooltip: "Long implied by" },
      { label: "\\Longleftrightarrow", latex: "\\Longleftrightarrow", tooltip: "Long iff" },
      { label: "\\uparrow", latex: "\\uparrow", tooltip: "Up arrow" },
      { label: "\\downarrow", latex: "\\downarrow", tooltip: "Down arrow" },
      { label: "\\updownarrow", latex: "\\updownarrow", tooltip: "Up-down arrow" },
      { label: "\\Uparrow", latex: "\\Uparrow", tooltip: "Double up arrow" },
      { label: "\\Downarrow", latex: "\\Downarrow", tooltip: "Double down arrow" },
      { label: "\\Updownarrow", latex: "\\Updownarrow", tooltip: "Double up-down arrow" },
      { label: "\\nearrow", latex: "\\nearrow", tooltip: "Northeast arrow" },
      { label: "\\searrow", latex: "\\searrow", tooltip: "Southeast arrow" },
      { label: "\\nwarrow", latex: "\\nwarrow", tooltip: "Northwest arrow" },
      { label: "\\swarrow", latex: "\\swarrow", tooltip: "Southwest arrow" },
      { label: "\\mapsto", latex: "\\mapsto", tooltip: "Maps to" },
      { label: "\\longmapsto", latex: "\\longmapsto", tooltip: "Long maps to" },
      { label: "\\hookleftarrow", latex: "\\hookleftarrow", tooltip: "Hook left arrow" },
      { label: "\\hookrightarrow", latex: "\\hookrightarrow", tooltip: "Hook right arrow" },
      { label: "\\leftharpoonup", latex: "\\leftharpoonup", tooltip: "Left harpoon up" },
      { label: "\\rightharpoonup", latex: "\\rightharpoonup", tooltip: "Right harpoon up" },
      { label: "\\leftharpoondown", latex: "\\leftharpoondown", tooltip: "Left harpoon down" },
      { label: "\\rightharpoondown", latex: "\\rightharpoondown", tooltip: "Right harpoon down" },
      { label: "\\rightleftharpoons", latex: "\\rightleftharpoons", tooltip: "Right-left harpoons" },
      { label: "\\twoheadleftarrow", latex: "\\twoheadleftarrow", tooltip: "Two-head left arrow" },
      { label: "\\twoheadrightarrow", latex: "\\twoheadrightarrow", tooltip: "Two-head right arrow" },
      { label: "\\leftleftarrows", latex: "\\leftleftarrows", tooltip: "Double left arrows" },
      { label: "\\rightrightarrows", latex: "\\rightrightarrows", tooltip: "Double right arrows" },
      { label: "\\leftrightarrows", latex: "\\leftrightarrows", tooltip: "Left-right paired arrows" },
      { label: "\\rightleftarrows", latex: "\\rightleftarrows", tooltip: "Right-left paired arrows" },
      { label: "\\upuparrows", latex: "\\upuparrows", tooltip: "Double up arrows" },
      { label: "\\downdownarrows", latex: "\\downdownarrows", tooltip: "Double down arrows" },
      { label: "\\looparrowleft", latex: "\\looparrowleft", tooltip: "Loop arrow left" },
      { label: "\\looparrowright", latex: "\\looparrowright", tooltip: "Loop arrow right" },
      { label: "\\circlearrowleft", latex: "\\circlearrowleft", tooltip: "Circle arrow left" },
      { label: "\\circlearrowright", latex: "\\circlearrowright", tooltip: "Circle arrow right" },
      { label: "\\curvearrowleft", latex: "\\curvearrowleft", tooltip: "Curve arrow left" },
      { label: "\\curvearrowright", latex: "\\curvearrowright", tooltip: "Curve arrow right" },
      { label: "\\rightsquigarrow", latex: "\\rightsquigarrow", tooltip: "Right squiggly arrow" },
      { label: "\\nleftarrow", latex: "\\nleftarrow", tooltip: "Not left arrow" },
      { label: "\\nrightarrow", latex: "\\nrightarrow", tooltip: "Not right arrow" },
      { label: "\\nLeftarrow", latex: "\\nLeftarrow", tooltip: "Not left double arrow" },
      { label: "\\nRightarrow", latex: "\\nRightarrow", tooltip: "Not right double arrow" },
      { label: "\\nleftrightarrow", latex: "\\nleftrightarrow", tooltip: "Not left-right arrow" },
      { label: "\\nLeftrightarrow", latex: "\\nLeftrightarrow", tooltip: "Not left-right double arrow" },
      { label: "\\xrightarrow{x}", latex: "\\xrightarrow{${1}}", tooltip: "Right arrow with text above" },
      { label: "\\xleftarrow{x}", latex: "\\xleftarrow{${1}}", tooltip: "Left arrow with text above" },
      { label: "\\leftrightharpoons", latex: "\\leftrightharpoons", tooltip: "Left-right harpoons ⇋" },
      { label: "\\leftrightsquigarrow", latex: "\\leftrightsquigarrow", tooltip: "Left-right squiggle ↭" },
      { label: "\\upharpoonleft", latex: "\\upharpoonleft", tooltip: "Up harpoon left ↿" },
      { label: "\\upharpoonright", latex: "\\upharpoonright", tooltip: "Up harpoon right ↾" },
      { label: "\\downharpoonleft", latex: "\\downharpoonleft", tooltip: "Down harpoon left ⇃" },
      { label: "\\downharpoonright", latex: "\\downharpoonright", tooltip: "Down harpoon right ⇂" },
      { label: "\\leftarrowtail", latex: "\\leftarrowtail", tooltip: "Left arrow tail ↢" },
      { label: "\\rightarrowtail", latex: "\\rightarrowtail", tooltip: "Right arrow tail ↣" },
      { label: "\\Lleftarrow", latex: "\\Lleftarrow", tooltip: "Triple left arrow ⇚" },
      { label: "\\Rrightarrow", latex: "\\Rrightarrow", tooltip: "Triple right arrow ⇛" },
      { label: "\\dashleftarrow", latex: "\\dashleftarrow", tooltip: "Dash left arrow ⇠" },
      { label: "\\dashrightarrow", latex: "\\dashrightarrow", tooltip: "Dash right arrow ⇢" },
      { label: "\\leadsto", latex: "\\leadsto", tooltip: "Leads to ⇝" },
      { label: "\\Lsh", latex: "\\Lsh", tooltip: "Left shift ↰" },
      { label: "\\Rsh", latex: "\\Rsh", tooltip: "Right shift ↱" },
      { label: "\\restriction", latex: "\\restriction", tooltip: "Restriction ↾" },
    ],
  },
  {
    category: "Accents",
    icon: "x̂",
    commands: [
      { label: "\\hat{x}", latex: "\\hat{${1}}", tooltip: "Hat" },
      { label: "\\bar{x}", latex: "\\bar{${1}}", tooltip: "Bar" },
      { label: "\\overline{x}", latex: "\\overline{${1}}", tooltip: "Overline" },
      { label: "\\underline{x}", latex: "\\underline{${1}}", tooltip: "Underline" },
      { label: "\\dot{x}", latex: "\\dot{${1}}", tooltip: "Dot" },
      { label: "\\ddot{x}", latex: "\\ddot{${1}}", tooltip: "Double dot" },
      { label: "\\vec{x}", latex: "\\vec{${1}}", tooltip: "Vector" },
      { label: "\\tilde{x}", latex: "\\tilde{${1}}", tooltip: "Tilde" },
      { label: "\\acute{x}", latex: "\\acute{${1}}", tooltip: "Acute" },
      { label: "\\grave{x}", latex: "\\grave{${1}}", tooltip: "Grave" },
      { label: "x'", latex: "${1}'", tooltip: "Prime" },
      { label: "x''", latex: "${1}''", tooltip: "Double prime" },
      { label: "\\mathring{x}", latex: "\\mathring{${1}}", tooltip: "Ring" },
      { label: "\\breve{x}", latex: "\\breve{${1}}", tooltip: "Breve" },
      { label: "\\check{x}", latex: "\\check{${1}}", tooltip: "Check" },
      { label: "\\dddot{x}", latex: "\\dddot{${1}}", tooltip: "Triple dot" },
      { label: "\\ddddot{x}", latex: "\\ddddot{${1}}", tooltip: "Quadruple dot" },
      { label: "x^{\\prime}", latex: "${1}^{\\prime}", tooltip: "Prime (superscript)" },
      { label: "\\widetilde{abc}", latex: "\\widetilde{${1}}", tooltip: "Wide tilde" },
      { label: "\\widehat{abc}", latex: "\\widehat{${1}}", tooltip: "Wide hat" },
      { label: "\\widecheck{abc}", latex: "\\widecheck{${1}}", tooltip: "Wide check (MathJax approximation)" },
      { label: "\\overbrace{x}^x", latex: "\\overbrace{${1}}^{${2}}", tooltip: "Overbrace" },
      { label: "\\underbrace{x}_y", latex: "\\underbrace{${1}}_{${2}}", tooltip: "Underbrace" },
      { label: "\\overleftarrow{x}", latex: "\\overleftarrow{${1}}", tooltip: "Left arrow over" },
      { label: "\\overrightarrow{x}", latex: "\\overrightarrow{${1}}", tooltip: "Right arrow over" },
      { label: "\\underleftarrow{x}", latex: "\\underleftarrow{${1}}", tooltip: "Left arrow under" },
      { label: "\\underrightarrow{x}", latex: "\\underrightarrow{${1}}", tooltip: "Right arrow under" },
      { label: "\\overleftrightarrow{AB}", latex: "\\overleftrightarrow{${1}}", tooltip: "Left-right arrow over" },
      { label: "\\underleftrightarrow{AB}", latex: "\\underleftrightarrow{${1}}", tooltip: "Left-right arrow under" },
      { label: "\\Overrightarrow{AB}", latex: "\\Overrightarrow{${1}}", tooltip: "Double right arrow over" },
      { label: "\\overleftharpoon{ac}", latex: "\\overleftharpoon{${1}}", tooltip: "Left harpoon over (MathJax approximation)" },
      { label: "\\overrightharpoon{ac}", latex: "\\overrightharpoon{${1}}", tooltip: "Right harpoon over (MathJax approximation)" },
      { label: "\\underbar{x}", latex: "\\underbar{${1}}", tooltip: "Underbar" },
      { label: "\\utilde{AB}", latex: "\\utilde{${1}}", tooltip: "Under tilde" },
      { label: "\\overgroup{AB}", latex: "\\overgroup{${1}}", tooltip: "Overgroup (MathJax approximation)" },
      { label: "\\undergroup{AB}", latex: "\\undergroup{${1}}", tooltip: "Undergroup (MathJax approximation)" },
    ],
  },
  {
    category: "Symbols",
    icon: "\\infty",
    commands: [
      { label: "\\infty", latex: "\\infty", tooltip: "Infinity ∞" },
      { label: "\\nabla", latex: "\\nabla", tooltip: "Nabla ∇" },
      {
        label: "\\emptyset",
        latex: "\\emptyset",
        tooltip: "Empty set",
        subcommands: [
          { label: "\\emptyset", latex: "\\emptyset", tooltip: "Empty set ∅" },
          { label: "\\varnothing", latex: "\\varnothing", tooltip: "Empty set variant ∅" },
        ],
      },
      { label: "\\top", latex: "\\top", tooltip: "Top ⊤" },
      { label: "\\bot", latex: "\\bot", tooltip: "Bottom ⊥" },
      { label: "\\imath", latex: "\\imath", tooltip: "Dotless i" },
      { label: "\\jmath", latex: "\\jmath", tooltip: "Dotless j" },
      { label: "\\ell", latex: "\\ell", tooltip: "Script ℓ" },
      { label: "\\Re", latex: "\\Re", tooltip: "Real part ℜ" },
      { label: "\\Im", latex: "\\Im", tooltip: "Imaginary part ℑ" },
      { label: "\\wp", latex: "\\wp", tooltip: "Weierstrass ℘" },
      { label: "\\aleph", latex: "\\aleph", tooltip: "Aleph ℵ" },
      { label: "\\beth", latex: "\\beth", tooltip: "Beth ℶ" },
      { label: "\\gimel", latex: "\\gimel", tooltip: "Gimel ℷ" },
      { label: "\\daleth", latex: "\\daleth", tooltip: "Daleth ℸ" },
      { label: "\\hbar", latex: "\\hbar", tooltip: "h-bar ℏ" },
      { label: "\\hslash", latex: "\\hslash", tooltip: "Planck constant ℏ" },
      { label: "\\eth", latex: "\\eth", tooltip: "Eth ð" },
      { label: "\\partial", latex: "\\partial", tooltip: "Partial ∂" },
      { label: "\\mho", latex: "\\mho", tooltip: "Mho ℧" },
      { label: "\\mathbb{N}", latex: "\\mathbb{N}", tooltip: "Natural numbers ℕ" },
      { label: "\\mathbb{Z}", latex: "\\mathbb{Z}", tooltip: "Integers ℤ" },
      { label: "\\mathbb{Q}", latex: "\\mathbb{Q}", tooltip: "Rational numbers ℚ" },
      { label: "\\mathbb{R}", latex: "\\mathbb{R}", tooltip: "Real numbers ℝ" },
      { label: "\\mathbb{C}", latex: "\\mathbb{C}", tooltip: "Complex numbers ℂ" },
      { label: "\\mathbb{P}", latex: "\\mathbb{P}", tooltip: "Probability ℙ" },
      { label: "\\Bbbk", latex: "\\Bbbk", tooltip: "Blackboard bold k" },
      { label: "\\Finv", latex: "\\Finv", tooltip: "Finv Ⅎ" },
      { label: "\\Game", latex: "\\Game", tooltip: "Game ⅁" },
      { label: "\\degree", latex: "\\degree", tooltip: "Degree °" },
      { label: "\\checkmark", latex: "\\checkmark", tooltip: "Checkmark ✓" },
      { label: "\\dagger", latex: "\\dagger", tooltip: "Dagger †" },
      { label: "\\ddagger", latex: "\\ddagger", tooltip: "Double dagger ‡" },
      { label: "\\textsection", latex: "\\textsection", tooltip: "Section §" },
      { label: "\\textparagraph", latex: "\\textparagraph", tooltip: "Paragraph ¶" },
      { label: "\\angle", latex: "\\angle", tooltip: "Angle ∠" },
      { label: "\\measuredangle", latex: "\\measuredangle", tooltip: "Measured angle ∡" },
      { label: "\\sphericalangle", latex: "\\sphericalangle", tooltip: "Spherical angle ∢" },
      { label: "\\surd", latex: "\\surd", tooltip: "Surd/radical √" },
      { label: "\\flat", latex: "\\flat", tooltip: "Flat ♭" },
      { label: "\\natural", latex: "\\natural", tooltip: "Natural ♮" },
      { label: "\\sharp", latex: "\\sharp", tooltip: "Sharp ♯" },
      { label: "\\%", latex: "\\%", tooltip: "Percent %" },
      { label: "\\#", latex: "\\#", tooltip: "Hash #" },
      { label: "\\&", latex: "\\&", tooltip: "Ampersand &" },
    ],
  },
  {
    category: "Fonts & Colors",
    icon: "\\mathbb{N}",
    commands: [
      { label: "\\mathrm{Ab}", latex: "\\mathrm{${1}}", tooltip: "Roman (upright)" },
      { label: "\\mathit{Ab}", latex: "\\mathit{${1}}", tooltip: "Italic" },
      { label: "\\mathbf{Ab}", latex: "\\mathbf{${1}}", tooltip: "Bold" },
      { label: "\\boldsymbol{AB}", latex: "\\boldsymbol{${1}}", tooltip: "Bold italic (symbols)" },
      { label: "\\mathsf{Ab}", latex: "\\mathsf{${1}}", tooltip: "Sans serif" },
      { label: "\\mathtt{Ab}", latex: "\\mathtt{${1}}", tooltip: "Monospace/Typewriter" },
      { label: "\\mathbb{AB}", latex: "\\mathbb{${1}}", tooltip: "Double-struck/Blackboard bold" },
      { label: "\\mathcal{AB}", latex: "\\mathcal{${1}}", tooltip: "Calligraphic/Script" },
      { label: "\\mathscr{AB}", latex: "\\mathscr{${1}}", tooltip: "Script" },
      { label: "\\mathfrak{Ab}", latex: "\\mathfrak{${1}}", tooltip: "Fraktur" },
      { label: "\\text{text}", latex: "\\text{${1}}", tooltip: "Text mode" },
      { label: "\\textbf{text}", latex: "\\textbf{${1}}", tooltip: "Text bold" },
      { label: "\\textit{text}", latex: "\\textit{${1}}", tooltip: "Text italic" },
      { label: "{\\color{red}x}", latex: "{\\color{red}${1}}", tooltip: "Red" },
      { label: "{\\color{blue}x}", latex: "{\\color{blue}${1}}", tooltip: "Blue" },
      { label: "{\\color{green}x}", latex: "{\\color{green}${1}}", tooltip: "Green" },
      { label: "{\\color{orange}x}", latex: "{\\color{orange}${1}}", tooltip: "Orange" },
      { label: "{\\color{purple}x}", latex: "{\\color{purple}${1}}", tooltip: "Purple" },
    ],
  },
  {
    category: "Shapes",
    icon: "\\heartsuit",
    commands: [
      { label: "\\clubsuit", latex: "\\clubsuit", tooltip: "Club suit ♣" },
      { label: "\\diamondsuit", latex: "\\diamondsuit", tooltip: "Diamond suit ♢" },
      { label: "\\heartsuit", latex: "\\heartsuit", tooltip: "Heart suit ♡" },
      { label: "\\spadesuit", latex: "\\spadesuit", tooltip: "Spade suit ♠" },
      { label: "\\maltese", latex: "\\maltese", tooltip: "Maltese cross ✠" },
      { label: "\\backslash", latex: "\\backslash", tooltip: "Backslash ∖" },
      { label: "\\diagup", latex: "\\diagup", tooltip: "Diagonal up ╱" },
      { label: "\\diagdown", latex: "\\diagdown", tooltip: "Diagonal down ╲" },
      { label: "\\prime", latex: "\\prime", tooltip: "Prime ′" },
      { label: "\\backprime", latex: "\\backprime", tooltip: "Back prime ‵" },
      { label: "\\colon", latex: "\\colon", tooltip: "Colon :" },
      { label: "\\diamond", latex: "\\diamond", tooltip: "Diamond ⋄" },
      { label: "\\lozenge", latex: "\\lozenge", tooltip: "Lozenge ◊" },
      { label: "\\blacklozenge", latex: "\\blacklozenge", tooltip: "Black diamond ⧫" },
      {
        label: "\\star",
        latex: "\\star",
        tooltip: "Star ☆",
        subcommands: [
          { label: "\\star", latex: "\\star", tooltip: "Star ☆" },
          { label: "\\bigstar", latex: "\\bigstar", tooltip: "Big star ★" },
        ],
      },
      { label: "\\triangleleft", latex: "\\triangleleft", tooltip: "Left triangle" },
      { label: "\\triangleright", latex: "\\triangleright", tooltip: "Right triangle" },
      { label: "\\blacktriangle", latex: "\\blacktriangle", tooltip: "Black triangle" },
      { label: "\\blacktriangledown", latex: "\\blacktriangledown", tooltip: "Black down triangle" },
      { label: "\\square", latex: "\\square", tooltip: "Square □" },
      { label: "\\blacksquare", latex: "\\blacksquare", tooltip: "Black square ■" },
      { label: "\\Box", latex: "\\Box", tooltip: "Box □" },
      {
        label: "\\triangle",
        latex: "\\triangle",
        tooltip: "Triangle △",
        subcommands: [
          { label: "\\triangle", latex: "\\triangle", tooltip: "Triangle △" },
          { label: "\\bigtriangleup", latex: "\\bigtriangleup", tooltip: "Big triangle up △" },
        ],
      },
      {
        label: "\\triangledown",
        latex: "\\triangledown",
        tooltip: "Triangle down ▽",
        subcommands: [
          { label: "\\triangledown", latex: "\\triangledown", tooltip: "Triangle down ▽" },
          { label: "\\bigtriangledown", latex: "\\bigtriangledown", tooltip: "Big triangle down ▽" },
        ],
      },
      { label: "\\blacktriangleleft", latex: "\\blacktriangleleft", tooltip: "Black triangle left ◀" },
      { label: "\\blacktriangleright", latex: "\\blacktriangleright", tooltip: "Black triangle right ▶" },
      { label: "\\Diamond", latex: "\\Diamond", tooltip: "Diamond ◊" },
      { label: "\\textcopyright", latex: "\\textcopyright", tooltip: "Copyright ©" },
      { label: "\\textregistered", latex: "\\textregistered", tooltip: "Registered ®" },
      { label: "\\ldots", latex: "\\ldots", tooltip: "Low dots …" },
      { label: "\\cdots", latex: "\\cdots", tooltip: "Center dots ⋯" },
      { label: "\\vdots", latex: "\\vdots", tooltip: "Vertical dots ⋮" },
      { label: "\\ddots", latex: "\\ddots", tooltip: "Diagonal dots ⋱" },
    ],
  },
];
